insert into state (nome) values ('AC');
insert into state (nome) values ('AL');
insert into state (nome) values ('AM');
insert into state (nome) values ('AP');
insert into state (nome) values ('BA');
insert into state (nome) values ('CE');
insert into state (nome) values ('DF');
insert into state (nome) values ('ES');
insert into state (nome) values ('GO');
insert into state (nome) values ('MA');
insert into state (nome) values ('MG');
insert into state (nome) values ('MS');
insert into state (nome) values ('MT');
insert into state (nome) values ('PA');
insert into state (nome) values ('PB');
insert into state (nome) values ('PE');
insert into state (nome) values ('PI');
insert into state (nome) values ('PR');
insert into state (nome) values ('RJ');
insert into state (nome) values ('RN');
insert into state (nome) values ('RO');
insert into state (nome) values ('RR');
insert into state (nome) values ('RS');
insert into state (nome) values ('SC');
insert into state (nome) values ('SE');
insert into state (nome) values ('SP');
insert into state (nome) values ('TO');

insert into product (nome,quantidade,valor_unitario) values('COCA COLA LATA 350ML', '50', '4.25');
insert into product (nome,quantidade,valor_unitario) values('CHOCOLATE KIT KAT WHITE NESTLE 41,5G', '100', '3.99');
insert into product (nome,quantidade,valor_unitario) values('CHOCOLATE KIT KAT 3 FINGERS CAPPUCCINO 41,5G', '100', '3.99');
insert into product (nome,quantidade,valor_unitario) values('CAIXA DE BALA DROPS HALLS SABOR CEREJA C/21 UNID', '100', '39.95');
insert into product (nome,quantidade,valor_unitario) values('SALGADINHO 300G DORITOS NACHO', '150', '21.89');
insert into product (nome,quantidade,valor_unitario) values('BATATA FRITA ONDULADA ORIGINAL RUFFLES PACOTE 115G', '150', '9.99');
insert into product (nome,quantidade,valor_unitario) values('BISCOITO RECHEADO DANIX SABOR CHOCOLATE 130G', '40', '3.49');
insert into product (nome,quantidade,valor_unitario) values('BISCOITO RECHEADO DANIX VITALICIO SABOR LEITE 86G', '40', '2.19');
insert into product (nome,quantidade,valor_unitario) values('AMENDOIM DORI JAPONES 200G', '45', '3.57');
insert into product (nome,quantidade,valor_unitario) values('CAIXA BOMBOM ESPECIALIDADES NESTLE 251G', '10', '13.99');
