insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
insert into estado (nome) values ("MG");
